'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {buildSeo,safeSite,token,tools}=require('../seo');
const cfg={url:'https://shipping-cost-optimizer-xiaoqiu3000.onrender.com/',version:'0.3.0',googleSiteVerification:'',bingSiteVerification:''};
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'shipping-seo-'));for(const route of tools){fs.mkdirSync(path.join(dir,route),{recursive:true});fs.writeFileSync(path.join(dir,route,'index.html'),'<html lang="en"><head><title>Test &amp; tool</title><meta name="description" content="Sample &amp; method"><link rel="canonical" href="https://old.example/"></head><body><a href="index.html">Home</a><footer class="footer">v0.2 · No AI API needed</footer></body></html>');}fs.writeFileSync(path.join(dir,'404.html'),'<html><title>Missing</title></html>');return dir;}
function output(fn,config=cfg){const dir=fixture();try{buildSeo(dir,config);fn(dir);}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('sitemap contains eight unique canonical URLs, not duplicate packaging path',()=>output(dir=>{const xml=fs.readFileSync(path.join(dir,'sitemap.xml'),'utf8');assert.equal((xml.match(/<loc>/g)||[]).length,8);assert.ok(!xml.includes('/packaging-optimizer/'));assert.ok(xml.includes(cfg.url));assert.ok(!xml.includes('<lastmod>'));}));
test('all calculator pages have exactly one canonical and version',()=>output(dir=>{for(const route of tools){const s=fs.readFileSync(path.join(dir,route,'index.html'),'utf8');assert.equal((s.match(/rel="canonical"/g)||[]).length,1);const expected=route==='packaging-optimizer'||!route?cfg.url:cfg.url+route+'/';assert.ok(s.includes('href="'+expected+'"'));assert.ok(s.includes('name="app-version" content="0.3.0"'));assert.ok(!s.includes('old.example'));}}));
test('robots advertises canonical sitemap',()=>output(dir=>assert.equal(fs.readFileSync(path.join(dir,'robots.txt'),'utf8'),'User-agent: *\nAllow: /\nSitemap: '+cfg.url+'sitemap.xml\n')));
test('public pages are server rendered and have headings without app scripts',()=>output(dir=>{for(const route of ['about','privacy','feedback','shipping-guide']){const s=fs.readFileSync(path.join(dir,route,'index.html'),'utf8');assert.equal((s.match(/<h1>/g)||[]).length,1);assert.ok(s.includes('rel="canonical"'));assert.ok(!s.includes('<script'));assert.ok(!s.includes('@@'));}}));
test('disabled verification leaves no placeholder verification claim',()=>output(dir=>{const s=fs.readFileSync(path.join(dir,'index.html'),'utf8');assert.ok(!s.includes('google-site-verification'));assert.ok(!s.includes('msvalidate.01'));}));
test('provided public verification tokens appear in the head',()=>output(dir=>{const s=fs.readFileSync(path.join(dir,'index.html'),'utf8');assert.ok(s.includes('name="google-site-verification" content="public_Test-123"'));assert.ok(s.indexOf('public_Test-123')<s.indexOf('</head>'));},{...cfg,googleSiteVerification:'public_Test-123'}));
test('feedback discloses account requirement, public issue and unbuilt feature',()=>output(dir=>{const s=fs.readFileSync(path.join(dir,'feedback','index.html'),'utf8');assert.ok(s.includes('issues/new?title='));assert.ok(s.includes('submitted issues are public'));assert.ok(s.includes('proposed feature, not an available product'));assert.ok(!s.includes('<form'));}));
test('release explicitly disables tracking and checkout',()=>output(dir=>{const r=JSON.parse(fs.readFileSync(path.join(dir,'release.json')));assert.equal(r.trackingEnabled,false);assert.equal(r.checkoutEnabled,false);assert.equal(r.pages,9);}));
test('HTML entities are not double encoded in Open Graph',()=>output(dir=>assert.ok(fs.readFileSync(path.join(dir,'index.html'),'utf8').includes('property="og:title" content="Test &amp; tool"'))));
test('404 carries noindex',()=>output(dir=>assert.ok(fs.readFileSync(path.join(dir,'404.html'),'utf8').includes('content="noindex"'))));
for(const value of ['http://example.com','https://u:p@example.com','https://example.com/a','https://example.com/?x=y','https://example.com/#x'])test('reject invalid site '+value,()=>assert.throws(()=>safeSite(value)));
for(const value of ['<meta name="x">','" onload="x','a\nb',true,{}])test('reject invalid token '+JSON.stringify(value),()=>assert.throws(()=>token(value)));
test('accept clean HTTPS origin',()=>assert.equal(safeSite(cfg.url).href,cfg.url));
